# Usar la imagen base de PHP con Apache
FROM alpine:latest

# Crear el directorio donde se almacenara los archivos estaticos
WORKDIR /var/www/html

# Copiar el código de la aplicación
COPY ./ /var/www/html/

